SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
BACKGROUND_COLOR = (0, 0, 0)  # Black color as an RGB tuple

# Setting for block #1
BLOCK_ONE_SIZE = 50
BLOCK_ONE_SPEED = 0
BLOCK_ONE_X = (SCREEN_WIDTH // 4) - (BLOCK_ONE_SIZE + 2)
BLOCK_ONE_Y = (SCREEN_HEIGHT // 2) - (BLOCK_ONE_SIZE + 2)
BLOCK_ONE_COLOR = (96, 96, 96)
BLOCK_ONE_MASS = 1 # KG

# Setting for block #2
BLOCK_TWO_SIZE = 100
BLOCK_TWO_SPEED = 3
BLOCK_TWO_X = (SCREEN_WIDTH // 2)
BLOCK_TWO_Y = (SCREEN_HEIGHT // 2) - (BLOCK_TWO_SIZE + 2)
BLOCK_TWO_COLOR = (224, 224, 224)
BLOCK_TWO_MASS = 100 # KG